source 'https://rubygems.org'

gem 'rails',                '4.1.0'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'rails-html-sanitizer'
gem 'sdoc',                 group: :doc
gem 'bootstrap-sass'
gem 'bcrypt'
gem 'better_errors'
gem 'binding_of_caller'
gem "therubyracer"
gem "less-rails"
gem 'sprockets-rails'
gem "compass-rails", "2.0.2"
gem 'high_voltage', '~> 2.2.1'
gem 'devise'
gem 'carrierwave'
gem 'carrierwave-video'
gem 'carrierwave-video-thumbnailer'
gem 'mini_magick'
gem 'date_validator'
gem 'validates_formatting_of'
gem 'chosen-rails'
gem 'twitter'
gem 'gmaps4rails'
gem 'geocoder'
gem 'cancancan', '~> 1.10'
gem 'omniauth-facebook' # Facebook authentication
gem "koala", "~> 1.10.0rc" # Facebook API
gem 'rails_admin'
gem 'yt', '~> 0.13.7'
gem 'rails-observers'
gem "omniauth-google-oauth2"
gem 'active_type', '0.3.1'
gem "jquery-fileupload-rails"


group :development, :test do
  gem 'mysql2'
  # gem 'byebug'
  gem 'web-console'
  gem 'spring'
  gem 'capistrano-rails', '~> 1.1.1'
end

group :test do
  gem 'minitest-reporters'
  gem 'mini_backtrace'
  gem 'guard-minitest'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
  gem 'unicorn'
end
